<?php

namespace App\Filament\Resources;

use App\Filament\Resources\StockInResource\Pages;
use App\Models\StockIn;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

class StockInResource extends Resource
{
    protected static ?string $model = StockIn::class;

    protected static ?string $navigationIcon = 'heroicon-o-arrow-down-circle';
    protected static ?string $navigationGroup = 'Stock Management';
    protected static ?int $navigationSort = 20;

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Select::make('warehouse_id')
                    ->relationship('warehouse', 'name')
                    ->required()
                    ->searchable()
                    ->preload(),

                Forms\Components\Select::make('supplier_id')
                    ->relationship('supplier', 'name')
                    ->searchable()
                    ->preload(),

                Forms\Components\Radio::make('reference_type')
                    ->label('Reference ID Type')
                    ->options([
                        'auto' => 'Auto Generated',
                        'manual' => 'Manual Input',
                    ])
                    ->default('auto')
                    ->inline()
                    ->live()
                    ->columnSpanFull(),

                Forms\Components\TextInput::make('reference_id')
                    ->disabled(fn(callable $get) => $get('reference_type') === 'auto')
                    ->dehydrated(fn(callable $get) => $get('reference_type') === 'manual')
                    ->required(fn(callable $get) => $get('reference_type') === 'manual')
                    ->placeholder(fn(callable $get) => $get('reference_type') === 'auto' ? 'Auto Generated by System' : 'Enter Reference ID')
                    ->maxLength(25)
                    ->columnSpanFull(),

                Forms\Components\Select::make('stock_in_status_id')
                    ->relationship('status', 'name')
                    ->required()
                    ->preload(),

                Forms\Components\Textarea::make('notes')
                    ->columnSpanFull(),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('warehouse.name')
                    ->searchable()
                    ->sortable(),
                Tables\Columns\TextColumn::make('supplier.name')
                    ->searchable()
                    ->sortable()
                    ->toggleable(),
                Tables\Columns\TextColumn::make('status.name')
                    ->sortable(),
                Tables\Columns\TextColumn::make('reference_type')
                    ->searchable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable(),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListStockIns::route('/'),
            'create' => Pages\CreateStockIn::route('/create'),
            'edit' => Pages\EditStockIn::route('/{record}/edit'),
        ];
    }
}
